# Generated by Django 3.2.8 on 2021-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('provider', models.CharField(max_length=200)),
                ('existences', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=60)),
            ],
        ),
    ]
