# Generated by Django 3.2.8 on 2021-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('telephone', models.PositiveIntegerField()),
                ('position', models.IntegerField(choices=[(1, 'Empleado'), (2, 'Administrador')], default=1)),
            ],
        ),
    ]
