# Generated by Django 3.2.8 on 2021-10-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_client', models.PositiveIntegerField()),
                ('shipping_address', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('number_article', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
